// todo-app-angular-workspace/projects/todo-app/src/app/components/todo-settings/pagination-settings/pagination-settings.component.ts
import { Component, OnInit } from '@angular/core';
import { Subscription } from 'rxjs';
import { Store } from '@ngrx/store';

import { IState, TodoListActions, selectSettings } from '../../../shared/state';
import { ISettings, PaginationType } from '../../../shared/models';

@Component({
  selector: 'app-pagination-settings',
  templateUrl: './pagination-settings.component.html',
  styleUrls: ['./pagination-settings.component.scss']
})
export class PaginationSettingsComponent implements OnInit {
  private settings: ISettings = {} as ISettings;
  readonly PaginationType: typeof PaginationType = PaginationType;
  paginationType!: PaginationType;
  maxVisiblePages!: number;
  isPaginationDisabled: boolean = false;
  private subscription!: Subscription;

  constructor(private store: Store<IState>) { }

  ngOnInit(): void {
    this.subscription = this.store.select(selectSettings)
        .pipe()
        .subscribe((settings: ISettings) => {
          this.paginationType = settings.pagination.paginationType;
          this.maxVisiblePages = settings.pagination.maxVisiblePages;
          this.isPaginationDisabled = !settings.general.isPaginationEnabled;
          this.settings = settings;
        });
  }

  ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }

  onSettingsUpdate(): void {
    this.store.dispatch(TodoListActions.settingsUpdated({
      payload: {
      ...this.settings,
        pagination: {
          paginationType: this.paginationType,
          maxVisiblePages: this.maxVisiblePages
        }
      }
    }));
  }

  onPaginationTypeChange(paginationType: PaginationType){
    this.paginationType = paginationType;
    this.onSettingsUpdate();
  }

  onMaxVisiblePagesChange(maxVisiblePages: number) {
    this.maxVisiblePages = maxVisiblePages;
    this.onSettingsUpdate();
  }
}

<div class='app__settings__group' [class]="{ 'app__settings__group--disabled': isPaginationDisabled }">
  <label class='app__settings__group-label' [class]="{ 'app__settings__group-label--disabled': isPaginationDisabled }">Pagination</label>
  <div class='app__settings__group__item' [class]="{ 'app__settings__group__item--disabled': isPaginationDisabled }">
    <div class="hstack gap-2">
      <label>Pagination type</label>
      <div
        class="btn-group ms-auto"
        dropdown>
        <button
          id="button-pagination-type"
          dropdownToggle
          type="button"
          class="action-button dropdown-toggle btn btn-outline-secondary"
          aria-controls="dropdown-paging"
          [disabled]="isPaginationDisabled"
        >
          {{paginationType}}
        </button>
        <ul id="dropdown-paging" *dropdownMenu class="dropdown-menu"
            role="menu" aria-labelledby="button-paging">
          <li role="menuitem" (click)="onPaginationTypeChange(PaginationType.Classic)">
            <a class="dropdown-item" href="#">{{ PaginationType.Classic }}</a>
          </li>
          <li role="menuitem" (click)="onPaginationTypeChange(PaginationType.Rotate)">
            <a class="dropdown-item" href="#">{{ PaginationType.Rotate }}</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class='app__settings__group__item' [class]="{ 'app__settings__group__item--disabled': isPaginationDisabled }">
    <div class="hstack gap-2">
      <label>Visible pages in navigation group</label>
      <div
        class="btn-group ms-auto"
        dropdown
      >
        <button
          id="button-visible-pages"
          dropdownToggle
          type="button"
          class="action-button dropdown-toggle btn btn-outline-secondary"
          aria-controls="dropdown-paging"
          [disabled]="isPaginationDisabled"
        >
          {{maxVisiblePages}}
        </button>
        <ul id="dropdown-paging" *dropdownMenu class="dropdown-menu"
            role="menu" aria-labelledby="button-paging">
          <li role="menuitem" (click)="onMaxVisiblePagesChange(1)"><a class="dropdown-item" href="#">1</a></li>
          <li role="menuitem" (click)="onMaxVisiblePagesChange(2)"><a class="dropdown-item" href="#">2</a></li>
          <li role="menuitem" (click)="onMaxVisiblePagesChange(3)"><a class="dropdown-item" href="#">3</a></li>
          <li role="menuitem" (click)="onMaxVisiblePagesChange(4)"><a class="dropdown-item" href="#">4</a></li>
          <li role="menuitem" (click)="onMaxVisiblePagesChange(5)"><a class="dropdown-item" href="#">5</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

// react-workspace/todo-react-app/src/components/TodoSettings/PaginationSettings/PaginationSettings.tsx
import { Dropdown, Stack } from "react-bootstrap";
import { useTodoList, useTodoListDispatch } from "../../../context/TodoListContext";
import { PaginationType } from "../../../models/ISettings";
import { IAction, TodoActions } from "../../../models/Action";

export function PaginationSettings() {
  const todoList = useTodoList();
  const dispatch = useTodoListDispatch();

  const ifDisabled = !todoList.settings.general.isPaginationEnabled;
  
  function handlePaginationTypeSelect(option: PaginationType) {
    dispatch({
      type: TodoActions.settingsUpdated,
      payload: {
        ...todoList.settings,
        pagination: {
          ...todoList.settings.pagination,
          paginationType: option
        }
      }
    } as IAction);
  }

  function handleVisiblePagesSelect(option: number) {
    dispatch({
      type: TodoActions.settingsUpdated,
      payload: {
        ...todoList.settings,
        pagination: {
          ...todoList.settings.pagination,
          maxVisiblePages: option
        }
      }
    } as IAction);
  }

  return (
    <div className={ ifDisabled ? 'App__settings__group App__settings__group--disabled' : 'App__settings__group'}>
      <label className={ ifDisabled ? 'App__settings__group-label App__settings__group-label--disabled' : 'App__settings__group-label' }>
        Pagination
      </label>
      <div className={ ifDisabled ? 'App__settings__group__item App__settings__group__item--disabled' : 'App__settings__group__item' }>
        <Stack direction="horizontal" gap={2}>
          <label>Pagination type</label>
          <Dropdown className="ms-auto">
            <Dropdown.Toggle
              data-testid="selected-pagination-type-option"
              variant="outline-secondary"
              className="action-button ps-2 pe-2"
              id="dropdown-pagination-type"
              disabled={ifDisabled}
            >
              {' '}{todoList.settings.pagination.paginationType}{' '}
            </Dropdown.Toggle>
            <Dropdown.Menu>
              <Dropdown.Item 
                data-testid="pagination-type-option-classic" 
                onClick={() => handlePaginationTypeSelect(PaginationType.Classic)}
              >
                { PaginationType.Classic }
              </Dropdown.Item>
              <Dropdown.Item 
                data-testid="pagination-type-option-rotate" 
                onClick={() => handlePaginationTypeSelect(PaginationType.Rotate)}
              >
                { PaginationType.Rotate }
              </Dropdown.Item>
            </Dropdown.Menu>
          </Dropdown>
        </Stack>
      </div>
      <div className={ ifDisabled ? 'App__settings__group__item App__settings__group__item--disabled' : 'App__settings__group__item' }>
        <Stack direction="horizontal" gap={2}>
          <label>Visible pages in navigation group</label>
          <Dropdown className="ms-auto">
            <Dropdown.Toggle
              data-testid="selected-visible-pages-option"
              variant="outline-secondary"
              className="action-button ps-2 pe-2"
              id="dropdown-visible-pages-number"
              disabled={ifDisabled}
            >
              {' '}{todoList.settings.pagination.maxVisiblePages}{' '}
            </Dropdown.Toggle>
            <Dropdown.Menu>
              <Dropdown.Item data-testid="visible-pages-option-1" onClick={() => handleVisiblePagesSelect(1)}>1</Dropdown.Item>
              <Dropdown.Item data-testid="visible-pages-option-2" onClick={() => handleVisiblePagesSelect(2)}>2</Dropdown.Item>
              <Dropdown.Item data-testid="visible-pages-option-3" onClick={() => handleVisiblePagesSelect(3)}>3</Dropdown.Item>
              <Dropdown.Item data-testid="visible-pages-option-4" onClick={() => handleVisiblePagesSelect(4)}>4</Dropdown.Item>
              <Dropdown.Item data-testid="visible-pages-option-5" onClick={() => handleVisiblePagesSelect(5)}>5</Dropdown.Item>
            </Dropdown.Menu>
          </Dropdown>
        </Stack>
      </div>
    </div>
  );
}
