// react-workspace/todo-react-app/src/components/Sort/Sorting.tsx
import { useState } from "react";
import { IAction, TodoActions } from "../../models/Action";
import { useTodoList, useTodoListDispatch } from "../../context/TodoListContext";
import { SortButton } from './SortButton';
import { ISort, SortDirection } from "../../models/ISort";

type Sort = {
  name: string,
  text: string
}

const sortByColumns: Sort[] = [
  {
    name: 'title',
    text: 'Title'
  } as Sort,
  {
    name: 'description',
    text: 'Description'
  } as Sort,
  {
    name: 'createdAt',
    text: 'Date'
  } as Sort,
  {
    name: 'completed',
    text: 'Completed'
  } as Sort
];

export function Sorting() {
  const todoList = useTodoList();
  const dispatch = useTodoListDispatch();
  const [activeColumn, setActiveColumn] = useState(todoList.sort.column);

  function handleSorting(column: string, direction: SortDirection) {
    setActiveColumn(column);
    dispatch({
      type: TodoActions.sort,
      payload: {
        sort: {
          column: column, 
          direction: direction
        } as ISort
      }
    } as IAction);
  }

  return (
    <>
    {todoList.activeTab !== 'settings' &&
      <section className="App__sorting d-flex flex-wrap">
        {
          sortByColumns.map((item: Sort) => (
            <SortButton 
              key={item.name}
              column={item.name}
              text={item.text}
              disabled={todoList.isLoading}
              sortDirection={activeColumn === item.name ? SortDirection.Asc : SortDirection.None}
              onClick={handleSorting}
            />
          ))
        }
      </section>
    }
    </>    
  );
}

// todo-app-angular-workspace/projects/todo-app/src/app/components/sorting/sorting.component.ts
import { Component, OnInit } from '@angular/core';

type Sort = {
  name: string,
  text: string
}

@Component({
  selector: 'app-sorting',
  templateUrl: './sorting.component.html',
  styleUrls: ['./sorting.component.scss']
})
export class SortingComponent implements OnInit {
  sortByColumns: Sort[] = [
    {
      name: 'title',
      text: 'Title'
    } as Sort,
    {
      name: 'description',
      text: 'Description'
    } as Sort,
    {
      name: 'createdAt',
      text: 'Date'
    } as Sort,
    {
      name: 'completed',
      text: 'Completed'
    } as Sort
  ];

  constructor() { }

  ngOnInit(): void { }
}

<section class="app__sorting d-flex flex-wrap">
  <app-sort-button
    *ngFor="let column of sortByColumns"
    [text]="column.text"
    [column]="column.name"
    [sortType]="column.sortType"
    [isActive]="activeColumn == column.name"
    [sortDirection]="activeColumn === column.name ? SortDirection.Asc : SortDirection.None"
    (onSort)="handleSort($event)"
  ></app-sort-button>
</section>
