// todo-app-angular-workspace/projects/todo-app/src/app/components/todo-settings/search-settings/search-settings.component.ts
import { Component, OnInit } from '@angular/core';
import { Subscription } from 'rxjs';
import { Store } from '@ngrx/store';

import { IState, TodoListActions, selectSettings } from '../../../shared/state';
import { ISettings } from '../../../shared/models';

@Component({
  selector: 'app-search-settings',
  templateUrl: './search-settings.component.html',
  styleUrls: ['./search-settings.component.scss']
})
export class SearchSettingsComponent implements OnInit {
  isSearchOnKeyPressEnabled: boolean = false;
  debounceTime: number = 500;
  private settings: ISettings = {} as ISettings;
  private subscription!: Subscription;

  constructor(private store: Store<IState>) { }

  ngOnInit(): void {
    this.subscription = this.store.select(selectSettings)
    .pipe()
    .subscribe((settings: ISettings) => {
      this.isSearchOnKeyPressEnabled = settings.search.isSearchOnKeyPressEnabled;
      this.debounceTime = settings.search.debounceTime;
      this.settings = settings;
    });
  }

  ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }

  onSettingsUpdate(): void {
    this.store.dispatch(TodoListActions.settingsUpdated({
      payload: {
      ...this.settings,
        search: {
          isSearchOnKeyPressEnabled: this.isSearchOnKeyPressEnabled,
          debounceTime: this.debounceTime
        }
      }
    }));
  }
}

<div class='app__settings__group'>
  <label class='app__settings__group-label'>Search</label>
  <div class='app__settings__group__item'>
    <div class="hstack gap-2">
      <label>Search on key press</label>
      <mat-slide-toggle class="ms-auto" [(ngModel)]="isSearchOnKeyPressEnabled" (click)="onSettingsUpdate()"></mat-slide-toggle>
    </div>
  </div>
  <div *ngIf="isSearchOnKeyPressEnabled" class='app__settings__group__item ms-5'>
    <div class="hstack gap-2">
      <label>Debounce time (ms)</label>
      <input
        type="number"
        class="form-control form-control-sm ms-auto"
        id="debounce-time"
        placeholder="Enter debounce time"
        [(ngModel)]="debounceTime"
        (change)="onSettingsUpdate()"
      />
    </div>
  </div>
</div>

// react-workspace/todo-react-app/src/components/TodoSettings/SearchSettings/SearchSettings.tsx
import { Form, Stack } from "react-bootstrap";
import { useTodoList, useTodoListDispatch } from "../../../context/TodoListContext";
import { ISearchSettings } from "../../../models/ISettings";
import { IAction, TodoActions } from "../../../models/Action";

export function SearchSettings() {
  const todoList = useTodoList();
  const dispatch = useTodoListDispatch();

  function handleSettingsUpdate(settingsPayload: ISearchSettings) {
    dispatch({
      type: TodoActions.settingsUpdated,
      payload: {
        ...todoList.settings,
        search: {...settingsPayload}
      }
    } as IAction);
  }

  return (
    <div className='App__settings__group'>
      <label className='App__settings__group-label'>Search</label>
      <div className='App__settings__group__item'>
        <Stack direction="horizontal" gap={2}>
          <label>Search on key press</label>
          <Form.Check 
            className='ms-auto'
            data-testid="search-on-keypress-switch"
            type="switch"
            id={`keyPress-switch`}
            checked={todoList.settings.search.isSearchOnKeyPressEnabled}
            onChange={(e) => {
              handleSettingsUpdate({
                ...todoList.settings.search,
                isSearchOnKeyPressEnabled: e.target.checked
              });
            }}
          /> 
        </Stack>
      </div>
      { todoList.settings.search.isSearchOnKeyPressEnabled &&
        <div className='App__settings__group__item ms-5'>
          <Stack direction="horizontal" gap={2}>
            <label>Debounce time (ms)</label>
            <Form.Control
              className="ms-auto"
              data-testid="debounce-time-input"
              type="number" 
              placeholder={'0'} 
              size="sm" 
              value={todoList.settings.search.debounceTime}
              onChange={(e) => {
                handleSettingsUpdate({
                  ...todoList.settings.search,
                  debounceTime: +e.target.value
                });
              }}
            />
          </Stack>
        </div>
      }
    </div>
  );
}
