// react-workspace/todo-react-app/src/components/AddTodo.tsx
import { Button, Col, Container, Form, Row, Stack } from 'react-bootstrap';
import { useState } from 'react';
import { useTodoListDispatch } from '../context/TodosContext';

export function AddTodo() {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');

  const dispatch = useTodoListDispatch();

  function handleAdd() {
    dispatch({
      type: 'added',
      title, 
      description
    });
    setTitle('');
    setDescription('');
  }
  
  return (
    <Form className="todo-background p-1">
      <Container fluid>
        <Row xs={1} sm={3}>
          <Col sm={5} className="p-2">
            <Form.Control 
              id="title"
              name="title"
              type="text" 
              placeholder="Enter title" 
              size="sm" 
              value={title}
              onChange={(e) => setTitle(e.target.value)} 
            />
          </Col>
          <Col sm={5} className="p-2">
            <Form.Control 
              id="description"
              name="description"
              type="text" 
              placeholder="Enter description" 
              size="sm" 
              value={description}
              onChange={(e) => setDescription(e.target.value)} 
            />
          </Col>
          <Col sm={2} className="p-2">
            <Button 
              variant="warning"
              style={{ 
                backgroundColor: '#FE9801',
                color: 'white', 
                minWidth: '90px',
                borderRadius: '20px',
                width: '100%'
              }} 
              size="sm"
              disabled={!title || title.trim() === '' || !description || description.trim() === ''}
              onClick={handleAdd}
            >
              Add
            </Button>
          </Col>
        </Row>
      </Container>
    </Form>
  )
}

// todo-app-angular-workspace/projects/todo-app/src/app/add-todo/add-todo.component.ts
import { Store } from '@ngrx/store';
import { Component, OnInit } from '@angular/core';
import { TodosActions } from '../state/todos.actions';

@Component({
  selector: 'app-add-todo',
  templateUrl: './add-todo.component.html',
  styleUrls: ['./add-todo.component.scss']
})
export class AddTodoComponent implements OnInit {
  addButton = { 
    backgroundColor: '#FE9801',
    color: 'white', 
    minWidth: '90px',
    borderRadius: '20px',
    width: '100%'
  };
  title = ''
  description = ''

  constructor(private store: Store) { }

  ngOnInit(): void { }
  
  onAdd() {
    this.store.dispatch(TodosActions.addTodo({
      title: this.title,
      description: this.description,
    }));
    // console.log(todo);
  }

  get buttonState(): boolean {
    return !this.title 
      || this.title.trim() === '' 
      || !this.description 
      || this.description.trim() === ''
  }
}

<div class="row p-1">
  <div class="col-12 col-sm-5 p-2">
    <input 
      type="text" 
      class="form-control form-control-sm" 
      id="title" 
      placeholder="Enter title"
      [(ngModel)]="title"
    />
  </div>
  <div class="col-12 col-sm-5 p-2">
    <input 
      type="text" 
      class="form-control form-control-sm" 
      id="description" 
      placeholder="Enter description"
      [(ngModel)]="description"
    />
  </div>
  <div class="col-12 col-sm-2 p-2">
    <button 
      type="submit" 
      class="btn btn-sm btn-warning"
      [ngStyle]="addButton"
      [disabled]="buttonState"
      (click)="onAdd()"
    >
      Add
    </button>
  </div>
</div>
