// react-workspace/todo-react-app/src/components/Tabs/Tabs.tsx
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faSearch, faAdd, faFilter, faDownload, IconDefinition } from '@fortawesome/free-solid-svg-icons';
import { Stack } from "react-bootstrap";
import { useState } from "react";

import { AddTodo } from '../AddTodo/AddTodo';
import { Search } from '../Search/Search';
import { FilterTodos } from '../Filter/FilterTodos';
import { ImportExport } from '../ImportExport/ImportExport';
import { useTodoList } from "../../context/TodoListContext";

type Tab = {
  name: string,
  icon: IconDefinition,
  content: JSX.Element
}

export function Tabs() {
  const [active, setActive] = useState('add-todo');
  const todoList = useTodoList();

  const tabs: Tab[] = [{
      name: 'add-todo',
      icon: faAdd,
      content: <AddTodo/>
    } as Tab,
    {
      name: 'search-todos',
      icon: faSearch,
      content: <Search placeholder='Search by title or description' />
    } as Tab,
    {
      name: 'filter-todos',
      icon: faFilter,
      content: <FilterTodos filter={todoList.filter}/>
    },
    {
      name: 'import-export',
      icon: faDownload,
      content: <ImportExport/>
    } as Tab
  ] as Tab [];  
  const activeChild = tabs.find((item: Tab) => item.name === active);

  return (
    <section className="App__tabs mb-2" data-testid="tabs">
      <section className='App__tabs__header'>
        <Stack direction="horizontal" gap={1} className='align-items-end'>      
          {tabs.map((tab: Tab) => (
            <div 
              data-testid={tab.name}
              key={tab.name}
              className={ 
                active === tab.name 
                ? "App__tabs__item" 
                : "App__tabs__item App__tabs__item--inactive"
              } 
              onClick={()=> setActive(tab.name)}
            >      
              <FontAwesomeIcon icon={tab.icon} />
            </div>
          ))}
        </Stack>
      </section>      
      <section className="App__tabs__content">
        <div 
          data-testid={"tab-content-" + activeChild?.name}
          key={"tab-content-" + activeChild?.name}
          className=""
        >
          {activeChild?.content}
        </div>
      </section>     
    </section>
  )
}

// todo-app-angular-workspace/projects/todo-app/src/app/components/tabs/tabs.component.ts
import { Component } from '@angular/core';
import { faAdd, faSearch, faFilter, faDownload, IconDefinition } from '@fortawesome/free-solid-svg-icons';

type Tab = {
  name: string,
  icon: IconDefinition,
}

@Component({
  selector: 'app-tabs',
  templateUrl: './tabs.component.html',
  styleUrls: ['./tabs.component.scss']
})
export class TabsComponent {
  tabs: Tab[] = [{
      name: 'add-todo',
      icon: faAdd,
    } as Tab,
    {
      name: 'search-todos',
      icon: faSearch
    } as Tab,
    {
      name: 'filter-todos',
      icon: faFilter
    } as Tab,
    {
      name: 'import-export',
      icon: faDownload
    } as Tab
  ];

  active = 'add-todo'

  setTab(name: string): void {
    this.active = name;
  }
}

<section class="app__tabs mb-2">
  <section class="app__tabs__header">
    <div id="tabs" class="hstack gap-1 align-items-end">
      <div
        *ngFor="let tab of tabs; trackBy:tabTrackBy"
        [id]="tab.name"
        class="app__tabs__item"
        [ngClass]="{'app__tabs__item--inactive': active !== tab.name}"
        (click)="setTab(tab.name)"
      >
        <fa-icon [icon]="tab.icon"></fa-icon>
      </div>
    </div>
  </section>
  <section class="app__tabs__content">
    <div class="todo-background">
      <app-add-todo *ngIf="active === 'add-todo'" class="fade-in"></app-add-todo>
      <app-search-todos *ngIf="active === 'search-todos'" class="fade-in"></app-search-todos>
      <app-filter-todos *ngIf="active === 'filter-todos'" class=""></app-filter-todos>
      <app-import-export *ngIf="active === 'import-export'" class="fade-in"></app-import-export>
      <app-todo-settings *ngIf="active === 'todo-settings'" class="fade-in"></app-todo-settings>
    </div>
  </section>
</section>
