// react-workspace/todo-react-app/src/components/ImportExport.tsx
import { faFileExport, faFileImport } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { ChangeEvent, useRef, useState } from "react";
import { Button, Col, Container, Form, InputGroup, Row } from "react-bootstrap";
import { useTodoList, useTodoListDispatch } from "../context/TodoListContext";
import { IAction } from "../models/Action";
import { ITodo, Todo } from "../models/Todo";

const fileReader = new FileReader();

export function ImportExport() {
  const todoList = useTodoList();
  const dispatch = useTodoListDispatch();
  
  const [file, setFile] = useState<File | null>(null);
  const fileRef = useRef(null as HTMLInputElement | null);

  function handleImport() {
    if (!file) 
      return;

    fileReader.readAsText(file);
  };

  function handleExport() {
    const link = document.createElement('a');
    const jsonContent = `data:text/json;chatset=utf-8,${encodeURIComponent(
      JSON.stringify(todoList.originalList)
    )}`;
    link.href = jsonContent;
    link.download = `todo-list-${new Date().toLocaleDateString()}-${new Date().toLocaleTimeString()}.json`;
    link.click();
  }

  fileReader.onload = (e: ProgressEvent<FileReader>) => {
    const text = e.target?.result;
    const list = JSON.parse(text as string) as Todo[];

    if (!(list instanceof Array)) {
      alert("Invalid JSON file content. Todo list should be an array.");
      return;
    }

    const importedTodoList = list.map((item: ITodo) => new Todo(item.id, 
                                                                item.title, 
                                                                item.description, 
                                                                item.completed, 
                                                                item.createdAt));

    if ((importedTodoList.length > 0 
        && (!(importedTodoList[0] instanceof Todo) 
         || !(Todo.validateFields(importedTodoList[0]))
            )
        )) {
      alert("Invalid JSON file content. Objects in array are not valid Todo objects.");
      return;
    }
          
    setFile(null);
    dispatch({
      type: 'imported',
      payload: {
        list: importedTodoList,
        activePage: 1
      }
    } as IAction);
    fileRef!.current!.value = '';
  };

  return (
    <Form className="todo-background p-1">
      <Container fluid>
        <Row xs={1} sm={3}>
          <Col sm={8} className="p-2">
            <InputGroup size="sm" className="">
              <Form.Control
                aria-label="Choose File"
                aria-describedby="inputGroup-sizing-sm"
                type={"file"} 
                accept={".json"} 
                ref={fileRef}
                onChange={(e: ChangeEvent<HTMLInputElement>) => {
                  setFile(((e.target).files![0]));
                }}
                readOnly 
              />
            </InputGroup>
          </Col>
          <Col sm={2} className="p-2">
            <Button 
              className="w-100 confirm-button"
              variant="outline-success" 
              size="sm"
              onClick={handleImport}
              disabled={!file}
            >
              Import {' '}
              <FontAwesomeIcon icon={faFileImport} />
            </Button>
          </Col>
          <Col sm={2} className="p-2">
            <Button 
              className="w-100 confirm-button"
              variant="outline-success" 
              size="sm"
              disabled={!todoList.originalList || todoList.originalList.length === 0}
              onClick={handleExport}
            >
              Export {' '}
              <FontAwesomeIcon icon={faFileExport} />
            </Button>
          </Col>
        </Row>
      </Container>
    </Form>
  )
}

// todo-app-angular-workspace/projects/todo-app/src/app/components/import-export/import-export.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { Store } from '@ngrx/store';
import { ITodoList } from '../../shared/models/todoList';
import { ITodo, Todo } from '../../shared/models/todo';
import { selectTodos } from '../../shared/state/todo.selectors';
import { faFileExport, faFileImport } from '@fortawesome/free-solid-svg-icons';
import { TodoListActions } from '../../shared/state/todo.actions';
import { Event } from '../../shared/models/event';

@Component({
  selector: 'app-import-export',
  templateUrl: './import-export.component.html',
  styleUrls: ['./import-export.component.scss']
})
export class ImportExportComponent implements OnInit {

  @ViewChild("fileContainer") fileContainer!: ElementRef<HTMLInputElement>;

  items: ITodo[] = [];
  file: File | null = null;
  fileReader = new FileReader();
  faFileImport = faFileImport;
  faFileExport = faFileExport;

  constructor(private store: Store<ITodoList>) { }

  ngOnInit(): void {
    this.store.select(selectTodos)
      .pipe()
      .subscribe((todoList: ITodoList) => this.items = todoList.originalList);

    this.fileReader.onload = this.onLoad;
  }

  onImport(): void {
    if (this.file === null)
      return;

    this.fileReader.readAsText(this.file);
  }

  onExport(): void {
    const link = document.createElement('a');
    const jsonContent = `data:text/json;chatset=utf-8,${encodeURIComponent(
      JSON.stringify(this.items)
    )}`;
    link.href = jsonContent;
    link.download = `todo-list-${new Date().toLocaleDateString()}-${new Date().toLocaleTimeString()}.json`;
    link.click();
  }

  onChooseFile(e: Event) {
    this.file = ((e.target) as HTMLInputElement).files![0];
  }

  onLoad = (e: ProgressEvent<FileReader>) => {
    const text = e.target?.result;
    const list = JSON.parse(text as string) as Todo[];

    if (!(list instanceof Array)) {
      alert("Invalid JSON file content. Todo list should be an array.");
      return;
    }

    const importedTodoList = list.map((item: Todo) => new Todo(item.id, 
                                                               item.title, 
                                                               item.description, 
                                                               item.completed, 
                                                               item.createdAt));

    if ((importedTodoList.length > 0 
        && (!(importedTodoList[0] instanceof Todo) 
         || !(Todo.validateFields(importedTodoList[0]))
            )
        )) {
      alert("Invalid JSON file content. Objects in array are not valid Todo objects.");
      return;
    }
          
    this.file = null;
    this.fileContainer.nativeElement.value = '';
    this.store.dispatch(TodoListActions.imported({ 
      activePage: 1,
      list: importedTodoList
    }));
  };
}

<div class="container-fluid">
  <div class="row p-1">
    <div class="col-12 col-sm-8 p-2">
      <div class="input-group">
        <input
          ngModel #fileContainer
          type="file"
          class="form-control form-control-sm"
          [style.cursor]="'pointer'"
          id="choose-file"
          accept=".json"
          readOnly
          (change)="onChooseFile($event)"
        />
      </div>
    </div>
    <div class="col-12 col-sm-2 p-2">
      <button
        id="import-button"
        type="button"
        class="btn btn-sm btn-outline-secondary action-button w-100"
        [disabled]="!this.file"
        (click)="onImport()"
      >
        Import
        <fa-icon [icon]="faFileImport"></fa-icon>
      </button>
    </div>
    <div class="col-12 col-sm-2 p-2">
      <button
        id="export-button"
        type="button"
        class="btn btn-sm btn-outline-secondary action-button w-100"
        [disabled]="ifExportDisabled"
        (click)="onExport()"
      >
        Export
        <fa-icon [icon]="faFileExport"></fa-icon>
      </button>
    </div>
  </div>
</div>
