// react-workspace/todo-react-app/src/components/Tabs.tsx
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faSearch, faAdd, faFilter, faDownload } from '@fortawesome/free-solid-svg-icons';
import { Stack } from "react-bootstrap";
import { useState } from "react";

export function Tabs({ children }: any) {
  const [active, setActive] = useState('add-todo');
  const activeChild = children.find((item: any) => item.key === active);
  const tabs = [{
    name: 'add-todo',
    icon: faAdd,
  },
  {
    name: 'search-todos',
    icon: faSearch
  },
  {
    name: 'filter-todos',
    icon: faFilter
  },
  {
    name: 'import-export',
    icon: faDownload
  }
];

  return (
    <section className="App__tabs mb-2">
      <Stack direction="horizontal" gap={1}>      
        {tabs.map((tab: any) => (
          <div 
            key={tab.name}
            className={ 
              active === tab.name 
              ? "App__tabs__item" 
              : "App__tabs__item App__tabs__item--inactive"
            } 
            onClick={()=> setActive(tab.name)}
          >      
            <FontAwesomeIcon icon={tab.icon} />
          </div>
        ))}
      </Stack>
      <section className="App__tabs-content">
        <div 
          key={"tab-content-" + activeChild.key}
          className="fade-in"
        >
          {activeChild}
        </div>
      </section>     
    </section>
  )
}

// todo-app-angular-workspace/projects/todo-app/src/app/tabs/tabs.component.ts
import { Component } from '@angular/core';
import { faAdd, faSearch, faFilter, faDownload } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-tabs',
  templateUrl: './tabs.component.html',
  styleUrls: ['./tabs.component.scss']
})
export class TabsComponent {
  tabs = [{
      name: 'add-todo',
      icon: faAdd,
    },
    {
      name: 'search-todos',
      icon: faSearch
    },
    {
      name: 'filter-todos',
      icon: faFilter
    },
    {
      name: 'import-export',
      icon: faDownload
    }
  ];

  active = 'add-todo'

  setTab(name: string): void {
    this.active = name;
  }
}

<!-- <mat-slide-toggle>Toggle me!</mat-slide-toggle> -->
<!-- <span class="mx-2">
  <fa-icon [icon]="faAdd"></fa-icon>
</span> -->

<section class="app__tabs mb-2">
  <div class="hstack gap-1">
    <div 
      *ngFor="let tab of tabs" 
      [ngClass]="active === tab.name ? 'app__tabs__item' : 'app__tabs__item app__tabs__item--inactive'"
      (click)="setTab(tab.name)"
    >
      <fa-icon [icon]="tab.icon"></fa-icon>
    </div>
  </div>
  <section class="app__tabs-content">
    <div class="container-fluid todo-background">
      <app-add-todo *ngIf="active === 'add-todo'" class="fade-in"></app-add-todo>
      <app-search-todos *ngIf="active === 'search-todos'" class="fade-in"></app-search-todos>   
    </div>
  </section>     
</section>
