// react-workspace/todo-react-app/src/components/TodoSettings/GeneralSettings/GeneralSettings.tsx
import { Dropdown, Form, Stack } from "react-bootstrap";

import { useTodoList, useTodoListDispatch } from "../../../context";
import { IAction, TodoActions, IGeneralSettings, ListContainerType } from "../../../models";

export type Props = {
  paginationSwitch: boolean;
  onPaginationSwitch: (enabled: boolean) => void
}

export function GeneralSettings() {
  const todoList = useTodoList();
  const dispatch = useTodoListDispatch();

  function handleSettingsUpdate(generalSettingsPayload: IGeneralSettings) {
    dispatch({
      type: TodoActions.settingsUpdated,
      payload: {
        ...todoList.settings,
        general: {...generalSettingsPayload}
      }
    } as IAction);
  }
  
  function handleListSizeSelect(otpion: ListContainerType) {
    handleSettingsUpdate({
      ...todoList.settings.general,
      listSizeType: otpion
    });
  }

  return (
    <div className='App__settings__group'>
      <label className='App__settings__group-label'>General</label>
      <div className='App__settings__group__item'>
        <Stack direction="horizontal" gap={2}>
          <label>Comfirm on change/remove</label>
          <Form.Check 
            className='ms-auto'
            type="switch"
            id="comfirm-enabled"
            data-testid="comfirm-enabled"
            checked={todoList.settings.general.isConfirmEnabled}
            onChange={(e) => {
              handleSettingsUpdate({
                ...todoList.settings.general,
                isConfirmEnabled: e.target.checked
              });
            }}
          /> 
        </Stack>
      </div>
      <div className='App__settings__group__item'>
        <Stack direction="horizontal" gap={2}>
          <label>Pagination</label>
          <Form.Check 
            className='ms-auto'
            type="switch"
            id="pagination-enabled"
            data-testid="pagination-enabled"
            checked={todoList.settings.general.isPaginationEnabled}
            onChange={(e) => {
              handleSettingsUpdate({
                ...todoList.settings.general,
                isPaginationEnabled: e.target.checked,
                isInfiniteScrollEnabled: false
              });
            }}
          /> 
        </Stack>
      </div>
      <div className='App__settings__group__item'>
        <Stack direction="horizontal" gap={2}>
          <label>Infinite Scroll</label>
          <Form.Check 
            className='ms-auto'
            type="switch"
            id="infinite-scroll-enabled"
            data-testid="infinite-scroll-enabled"
            checked={todoList.settings.general.isInfiniteScrollEnabled}
            onChange={(e) => {
              handleSettingsUpdate({
                ...todoList.settings.general,
                isPaginationEnabled: false,
                isInfiniteScrollEnabled: e.target.checked
              });
            }}
          /> 
        </Stack>
      </div>
      <div className='App__settings__group__item'>
        <Stack direction="horizontal" gap={2}>
          <label>List container size</label>
          <Dropdown className="ms-auto">
            <Dropdown.Toggle
              data-testid="list-size-dropdown"
              variant="outline-secondary"
              className="action-button ps-2 pe-2"
              id="dropdown-list-size-type"
              disabled={false}
            >
              {' '}{todoList.settings.general.listSizeType}{' '}
            </Dropdown.Toggle>
            <Dropdown.Menu>
              <Dropdown.Item 
                data-testid="list-size-option-fixed" 
                onClick={() => handleListSizeSelect(ListContainerType.Fixed)}
              >
                { ListContainerType.Fixed }
              </Dropdown.Item>
              <Dropdown.Item 
                data-testid="list-size-option-dynamic" 
                onClick={() => handleListSizeSelect(ListContainerType.Dynamic)}
                >
                  { ListContainerType.Dynamic }
                </Dropdown.Item>
            </Dropdown.Menu>
          </Dropdown>
        </Stack>
      </div>
      { todoList.settings.general.listSizeType === ListContainerType.Fixed &&
        <div className='App__settings__group__item ms-5'>
          <Stack direction="horizontal" gap={2}>
            <label>Size (px)</label>
            <Form.Control
              className="ms-auto"
              data-testid="list-size-input"
              type="number" 
              placeholder={'0'} 
              id="fixed-size"
              size="sm" 
              value={todoList.settings.general.fixedListSize}
              onChange={(e) => {
                handleSettingsUpdate({
                  ...todoList.settings.general,
                  fixedListSize: (+e.target.value)
                });
              }}
            />
          </Stack>
        </div>
      }      
    </div>
  );
}

// todo-app-angular-workspace/projects/todo-app/src/app/components/todo-settings/general-settings/general-settings.component.ts
import { Component, OnInit } from '@angular/core';
import { Store } from '@ngrx/store';
import { Subscription } from 'rxjs';

import { IGeneralSettings, ISettings, ListContainerType } from '../../../shared/models';
import { IState, TodoListActions, selectSettings } from '../../../shared/state';

@Component({
  selector: 'app-general-settings',
  templateUrl: './general-settings.component.html',
  styleUrls: ['./general-settings.component.scss']
})
export class GeneralSettingsComponent implements OnInit {
  isConfirmEnabled: boolean = true;
  isPaginationEnabled: boolean = true;
  isInfiniteScrollEnabled: boolean = false;
  listSizeType: ListContainerType = ListContainerType.Fixed;
  fixedListSize: number = 200;
  public readonly ListContainerType : typeof ListContainerType = ListContainerType;
  private settings: ISettings = {} as ISettings;
  private subscription!: Subscription;

  constructor(private store: Store<IState>) { }

  ngOnInit(): void {
    this.subscription = this.store.select(selectSettings)
        .pipe()
        .subscribe((settings: ISettings) => {
          this.isConfirmEnabled = settings.general.isConfirmEnabled;
          this.isPaginationEnabled = settings.general.isPaginationEnabled;
          this.isInfiniteScrollEnabled = settings.general.isInfiniteScrollEnabled;
          this.listSizeType = settings.general.listSizeType;
          this.fixedListSize = settings.general.fixedListSize;
          this.settings = settings;
        });
  }

  ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }

  onSettingsUpdate(generalSettingsPayload: IGeneralSettings): void {
    this.store.dispatch(TodoListActions.settingsUpdated({
      payload: {
      ...this.settings,
        general: { ...generalSettingsPayload }
      }
    }));
  }

  onListSizeTypeChange(listSizeType: ListContainerType) {
    this.listSizeType = listSizeType;
    this.onSettingsUpdate({
      ...this.settings.general,
      listSizeType: this.listSizeType
    });
  }

  onFixedListSizeChange() {
    this.onSettingsUpdate({
      ...this.settings.general,
      fixedListSize: this.fixedListSize
    });
  }
}

<div class='app__settings__group'>
  <label class='app__settings__group-label'>General</label>
  <div class='app__settings__group__item'>
    <div class="hstack gap-2">
      <label>Comfirm on change/remove</label>
      <mat-slide-toggle class="ms-auto" [(ngModel)]="isConfirmEnabled" (click)="onSettingsUpdate({
        isConfirmEnabled,
        isPaginationEnabled,
        isInfiniteScrollEnabled,
        listSizeType,
        fixedListSize
      })"></mat-slide-toggle>
    </div>
  </div>
  <div class='app__settings__group__item'>
    <div class="hstack gap-2">
      <label>Pagination</label>
      <mat-slide-toggle class="ms-auto" [(ngModel)]="isPaginationEnabled" (click)="onSettingsUpdate({
        isConfirmEnabled,
        isPaginationEnabled,
        isInfiniteScrollEnabled: false,
        listSizeType,
        fixedListSize
      })"></mat-slide-toggle>
    </div>
  </div>
  <div class='app__settings__group__item'>
    <div class="hstack gap-2">
      <label>Infinite Scroll</label>
      <mat-slide-toggle class="ms-auto" [(ngModel)]="isInfiniteScrollEnabled" (click)="onSettingsUpdate({
        isConfirmEnabled,
        isPaginationEnabled: false,
        isInfiniteScrollEnabled,
        listSizeType,
        fixedListSize
      })"></mat-slide-toggle>
    </div>
  </div>
  <div class='app__settings__group__item'>
    <div class="hstack gap-2">
      <label>List container size</label>
      <div
        class="btn-group ms-auto"
        dropdown
        [isDisabled]="false">
        <button
          id="button-list-size-type"
          dropdownToggle
          type="button"
          class="action-button dropdown-toggle btn btn-outline-secondary"
          aria-controls="dropdown-paging"
        >
          {{listSizeType}}
        </button>
        <ul id="dropdown-paging" *dropdownMenu class="dropdown-menu"
            role="menu" aria-labelledby="button-paging">
          <li role="menuitem" (click)="onListSizeTypeChange(ListContainerType.Fixed)"><a class="dropdown-item" href="#">{{ ListContainerType.Fixed }}</a></li>
          <li role="menuitem" (click)="onListSizeTypeChange(ListContainerType.Dynamic)"><a class="dropdown-item" href="#">{{ ListContainerType.Dynamic }}</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div *ngIf="listSizeType === ListContainerType.Fixed" class='app__settings__group__item ms-5'>
    <div class="hstack gap-2">
      <label>Size (px)</label>
      <input
        type="number"
        class="form-control form-control-sm ms-auto"
        id="list-size"
        placeholder="Enter size"
        [(ngModel)]="fixedListSize"
        (change)="onFixedListSizeChange()"
      />
    </div>
  </div>
</div>
