// react-workspace/todo-react-app/src/components/Loader/Loader.tsx
type Props = {
  height: number;
}

export function Loader({ height }: Props) {
  return (<div id="loader" data-testid="loader" style={{height: height + 'px'}} className='loader-container d-flex justify-content-center align-items-center fade-in'>
            <div className='loader'></div>
          </div>);
}

// todo-app-angular-workspace/projects/todo-app/src/app/components/loader/loader.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-loader',
  templateUrl: './loader.component.html',
  styleUrls: ['./loader.component.scss']
})
export class LoaderComponent {
  @Input() height: number = 280;
}

<div
  class="loader-container d-flex justify-content-center align-items-center fade-in"
  [ngStyle]="{'height': height + 'px'}"
>
  <div class="loader"></div>
</div>
