// react-workspace/todo-react-app/src/components/TodoItem/TodoItem.tsx
import { useState } from 'react';
import { Stack } from 'react-bootstrap';
import { faTrash, faCheckDouble } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useTodoListDispatch } from '../../context/TodoListContext';
import { IAction, TodoActions } from '../../models/Action';
import { ITodo } from '../../models/Todo';
import { ConfirmModal } from '../ConfirmModal/ConfirmModal';

type Props = {
  todo: ITodo;
};

export function TodoItem({ todo }: Props){
  const [showModal, setShowModal] = useState(false); 
  const [confirm, onConfirm] = useState(null as any);   
  const [confirmDialogText, setConfirmDialogText] = useState(''); 
  const dispatch = useTodoListDispatch();

  let handleComplete = () => {
    dispatch({
      type: TodoActions.changed,
      payload: {
        todo: {...todo, completed: true}
      }
    } as IAction);
  }

  let handleDelete = () => {
    dispatch({
      type: TodoActions.deleted,
      payload: {
        id: todo.id
      }                
    } as IAction);
  }


  return (
      <div className="App__todo-list__item">
        <Stack direction="horizontal" gap={3}>
          <div>
            <div className={ todo.completed 
                ? "App__todo-list__item-title--completed" 
                : "App__todo-list__item-title" 
            }>
              { todo.title }
            </div>
            <div className={
              todo.completed 
                ? "App__todo-list__item-description--compleated" 
                : "App__todo-list__item-description"
              }>
                <span>{todo.description}</span>
                { todo.createdAt && 
                  <span>
                    {' (' + new Date(todo.createdAt).toDateString() + ')'}
                  </span> 
                }
            </div>
          </div>
          <div className="ms-auto">
            <FontAwesomeIcon 
              icon={faCheckDouble} 
              className={todo.completed ? "action-icon--disabled" : "action-icon"}
              onClick={() => {
                if (todo.completed)
                  return;

                onConfirm(() => handleComplete);
                setConfirmDialogText('Are you sure you want to complete this item?');
                setShowModal(true);
              }}
            />
          </div>
          <div>
            <FontAwesomeIcon 
              icon={faTrash} 
              className="action-icon"
              onClick={() => {
                onConfirm(() => handleDelete);
                setConfirmDialogText('Are you sure you want to delete this item?');
                setShowModal(true);
              }}
            />
          </div>          
        </Stack>
        <ConfirmModal 
          content={confirmDialogText} 
          show={showModal}
          onConfirm={() => { 
            confirm(); 
            setShowModal(false);
          }}
          onCancel={() => { setShowModal(false) }}
        />
      </div>
  )
}

// todo-app-angular-workspace/projects/todo-app/src/app/components/todo-item/todo-item.component.ts
import { Store } from '@ngrx/store';
import { Component, Input } from '@angular/core';
import { first } from 'rxjs';
import { faCheckDouble, faTrash } from '@fortawesome/free-solid-svg-icons';

import { ITodo } from '../../shared/models/todo';
import { TodoListActions } from '../../shared/state/todo.actions';
import { IState } from '../../shared/state/state';
import { ConfirmModalService } from '../confirm-modal/confirm-modal.service';

@Component({
  selector: 'app-todo-item',
  templateUrl: './todo-item.component.html',
  styleUrls: ['./todo-item.component.scss']
})
export class TodoItemComponent {
  @Input() todo: ITodo = {} as ITodo;
  faCheckDouble = faCheckDouble;
  faTrash = faTrash;

  constructor(private store: Store<IState>, private modalService: ConfirmModalService) {}

  onComplete(todoId: number) {
    if (this.todo.completed)
      return;

    this.modalService.confirm('Are you sure you want to complete this item?', 'modal-sm')
    .pipe(first())
    .subscribe((confirmed) => {
      if (confirmed) {
        this.store.dispatch(TodoListActions.completed({ todoId }));
      }      
    });    
  }

  onRemove(todoId: number) {
    this.modalService.confirm('Are you sure you want to delete this item?', 'modal-sm')
    .pipe(first())
    .subscribe((confirmed) => {
      if (confirmed) {
        this.store.dispatch(TodoListActions.removed({ todoId }));
      }      
    }); 
  }
}

<div class="app__todo-list__item">
  <div class="hstack gap-3">
    <div class="">
      <div [ngClass]="todo.completed ? 'app__todo-list__item-title--completed' : 'app__todo-list__item-title'">
        {{ todo.title }}
      </div>
      <div [ngClass]="todo.completed ? 'app__todo-list__item-description--compleated' : 'app__todo-list__item-description'">
        <span>{{ todo.description }}</span>
        {{ ' ' }}
        <span>{{ todo.createdAt | date }}</span>
      </div>
    </div>
    <div class="ms-auto">
      <fa-icon 
        [icon]="faCheckDouble"
        [ngClass]="todo.completed ? 'action-icon--disabled' : 'action-icon'"
        (click)="onComplete(todo.id)"
      ></fa-icon>
    </div>
    <div [ngClass]="{'ms-todo' : todo.completed}">
      <fa-icon 
        [icon]="faTrash"
        class="action-icon"
        (click)="onRemove(todo.id)"
      ></fa-icon>
    </div>
  </div>
</div>
