// todo-app-angular-workspace/projects/todo-app/src/app/components/todo-list/todo-list.component.ts
import { Store } from '@ngrx/store';
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Observable, Subject, Subscription, combineLatestWith, delay } from 'rxjs';
import { faAngleDown } from '@fortawesome/free-solid-svg-icons';

import { DisplayMode, IState, TodoListActions, selectLoader, selectTodoDisplayList, selectTodos } from '../../shared/state';
import { IPaging, ISettings,  ITodo,  ListContainerType } from '../../shared/models';

@Component({
  selector: 'app-todo-list',
  templateUrl: './todo-list.component.html',
  styleUrls: ['./todo-list.component.scss'],
})
export class TodoListComponent implements OnInit, OnDestroy {

  public readonly ListContainerType : typeof ListContainerType = ListContainerType;
  public readonly DisplayMode : typeof DisplayMode = DisplayMode;

  readonly todoItemheight = 55;
  faAngleDown = faAngleDown;

  settings?: ISettings;
  items: Array<ITodo> = [];
  originalItems: Array<ITodo> = [];
  listSizeType?: ListContainerType;
  displayMode: DisplayMode = DisplayMode.All;
  paging?: IPaging = undefined;
  infiniteScroll = {
    startIndex: 0,
    endIndex: 5,
    isLoading: false,
    fetch: new Subject<number>()
  };

  isLoading$: Observable<boolean> = this.store.select(selectLoader);
  todoState$: Observable<IState> = this.store.select(selectTodos);

  private subscriptions: Subscription[] = [];

  constructor(private store: Store<IState>) { }

  ngOnInit(): void {
    window.addEventListener('scroll', this.handleScroll);

    this.subscriptions.push(this.todoState$.pipe().subscribe((state: IState) => {
      this.settings = state.settings;
      this.paging = state.paging;
      this.originalItems = state.originalList;
      this.displayMode = state.displayMode;

      if (state.settings.general.isPaginationEnabled) {
        this.items = [...state.displayList.slice(state.paging.startIndex, state.paging.endIndex)];
        return;
      }

      if (state.settings.general.isInfiniteScrollEnabled && this.listSizeType != state.settings.general.listSizeType) {
        this.infiniteScroll = {
          ...this.infiniteScroll,
          endIndex: this.calculateinfiniteScrollEndIndex(state.settings),
          isLoading: false
        };
        this.listSizeType = state.settings.general.listSizeType;
        this.items = [...state.displayList.slice(0, this.infiniteScroll.endIndex)];
        return;
      }

      if (state.settings.general.isInfiniteScrollEnabled) {
        this.items = [...state.displayList.slice(0, this.infiniteScroll.endIndex)];
        return;
      }

      this.items = [...state.displayList];
    }));

    this.subscriptions.push(this.store.select(selectTodoDisplayList)
      .pipe(
        combineLatestWith(this.infiniteScroll.fetch),
        delay(1000)
      )
      .subscribe(([items, endIndex]: [Array<ITodo>, number]) => {
        this.infiniteScroll = {...this.infiniteScroll, endIndex: endIndex + 5, isLoading: false};
        this.items = items.slice(0, this.infiniteScroll.endIndex );
      })
    );
  }

  ngOnDestroy(): void {
    window.removeEventListener('scroll', this.handleScroll);
    this.subscriptions.forEach(sub => sub.unsubscribe());
  }

  handleScroll = () => {
    if (!this.settings?.general?.isInfiniteScrollEnabled || this.infiniteScroll.isLoading) {
      return;
    }

    let { scrollTop, clientHeight, scrollHeight } = document.documentElement;

    if (this.settings?.general?.listSizeType === ListContainerType.Fixed) {
      scrollTop = document.getElementById('todo-list-container')!.scrollTop;
      clientHeight = document.getElementById('todo-list-container')!.clientHeight;
      scrollHeight = document.getElementById('todo-list-container')!.scrollHeight;
    }

    if ((scrollTop + clientHeight >= scrollHeight - 20)
     && !this.infiniteScroll.isLoading
     && this.infiniteScroll.endIndex < this.originalItems.length) {
      this.infiniteScroll = {...this.infiniteScroll, isLoading: true };
      this.infiniteScroll.fetch.next(this.infiniteScroll.endIndex);
    }
  };

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  drop(event: any) {
    const previousindex = event.previousIndex;
    const currentIndex = event.currentIndex;

    const items = this.reorder(
      this.originalItems,
      previousindex,
      currentIndex
    );

   const list = [];
   let counter = 1;

   for (const item of items) {
    list.push({...item, sortId: counter++});
   }

    this.store.dispatch(TodoListActions.manuallySorted({ list }));
  }

  private calculateinfiniteScrollEndIndex(settings: ISettings): number {
    return (settings.general.listSizeType === ListContainerType.Fixed
      ? ((settings.general.fixedListSize) / this.todoItemheight)
      : (document.documentElement.clientHeight - 200) / this.todoItemheight);
  }

  private reorder = (list: Array<ITodo>, startIndex: number, endIndex: number) => {
    if (this.settings?.general.isPaginationEnabled && this.paging) {
      startIndex = startIndex + ((this.paging.activePage - 1) * this.paging.itemsPerPage);
      endIndex =  endIndex + ((this.paging.activePage - 1)  * this.paging.itemsPerPage);
    }

    const result = Array.from(list);
    const [removed] = result.splice(startIndex, 1);
    result.splice(endIndex, 0, removed);

    return result;
  };
}

<section
  id="todo-list-container"
  (scroll)="handleScroll()"
  class="app__todo-list"
  [style]="settings?.general?.listSizeType == ListContainerType.Fixed
  ? {
      height: '' + settings?.general?.fixedListSize + 'px',
      overflow: 'overlay'
    }
  : {}"
>
  <app-loader *ngIf="isLoading$ | async" class=""></app-loader>
  <section
    *ngIf="(isLoading$ | async) === false"
    cdkDropList
    (cdkDropListDropped)="drop($event)"
    class="drag-list"
  >
    <div
      *ngFor="let item of items"
      cdkDrag [cdkDragDisabled]="displayMode === DisplayMode.Filtered"
      [class]="{'drag-box': displayMode === DisplayMode.All}"
    >
      <app-todo-item [todo]="item"></app-todo-item>
      <div class="drag-custom-placeholder" *cdkDragPlaceholder></div>
    </div>
    <div *ngIf="items.length === 0" class='text-light mt-5 mb-5'>No data</div>
    <app-loader [height]="150" *ngIf="infiniteScroll.isLoading && settings?.general?.isInfiniteScrollEnabled" class="fade-in"></app-loader>
  </section>
  <div
    *ngIf="settings?.general?.isInfiniteScrollEnabled
        && !infiniteScroll.isLoading
        && (isLoading$ | async) === false
        && (infiniteScroll.endIndex < originalItems.length)
        && displayMode === DisplayMode.All"
    id="infinite-scroll-end"
    class="app__todo-list__infinite-scroll-end"
  >
    <div class="app__todo-list__infinite-scroll-end--bouncing">
      <fa-icon
        [icon]="faAngleDown"
      ></fa-icon>
      <div>Scroll down to load more</div>
    </div>
  </div>
</section>

// react-workspace/todo-react-app/src/components/TodoList/TodoList.tsx
import { useEffect, useState } from 'react';
import { Subject, delay } from 'rxjs';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faAngleDown } from '@fortawesome/free-solid-svg-icons';
import { DragDropContext, Droppable, Draggable } from 'react-beautiful-dnd';

import { ITodo, IAction, TodoActions, ListContainerType } from '../../models';
import { DisplayMode, useTodoList, useTodoListDispatch } from '../../context';
import { ITodoListProvider } from '../../providers';
import { Loader, TodoItem } from '../';
import { useTodoListEffect } from '../../hooks';

type Props = {
  todoListProvider: ITodoListProvider
};

export function TodoList({ todoListProvider }: Props) {
  const todoList = useTodoList();
  const dispatch = useTodoListDispatch();
  const todoItemheight = 55;

  const [infiniteScroll, setInfiniteScroll] = useState({ 
    startIndex: 0, 
    endIndex: calculateinfiniteScrollEndIndex(),
    isLoading: false,
    fetch: new Subject<number>()
  });

  useTodoListEffect(todoList, todoListProvider, dispatch);

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  });

  useEffect(() => {
    const subscription = infiniteScroll.fetch
      .pipe(
        delay(1000), // TODO: switchMap to http request which whill load data from BE
      )
      .subscribe((endIndex: number) => {
        setInfiniteScroll({...infiniteScroll, endIndex: endIndex + 5, isLoading: false});
      });

    return () => subscription.unsubscribe();
  }, []);

  useEffect(() => {
    setInfiniteScroll({
      startIndex: 0, 
      endIndex: calculateinfiniteScrollEndIndex(),
      isLoading: false,
      fetch: infiniteScroll.fetch
    });
  }, [todoList.settings.general.listSizeType]);

  function calculateinfiniteScrollEndIndex(): number {
    return (todoList.settings.general.listSizeType === ListContainerType.Fixed  
      ? ((todoList.settings.general.fixedListSize) / todoItemheight)
      : (document.documentElement.clientHeight - 200) / todoItemheight);
  }

  function getDisplayList() {
    let items = [];
    if (todoList.settings.general.isPaginationEnabled) {
      items = todoList.displayList
        .slice(todoList.paging.startIndex, todoList.paging.endIndex);
    } else if (todoList.settings.general.isInfiniteScrollEnabled) {
      items = todoList.displayList
        .slice(infiniteScroll.startIndex, infiniteScroll.endIndex);
    } else {
      items = todoList.displayList;
    }    

    return items.map((item: ITodo, index: number) =>
    <Draggable 
      key={item.id} 
      draggableId={`item-${item.id}`} 
      index={index} 
      isDragDisabled={todoList.displayMode === DisplayMode.Filtered}
    >
      {(provided, snapshot) => ( 
        <div
          ref={provided.innerRef}
          {...provided.draggableProps}
          {...provided.dragHandleProps}
          style={getItemStyle(
            snapshot.isDragging,
            provided.draggableProps.style
          )}
        >
          <TodoItem 
            key={item.id} 
            todo={item}
          /> 
        </div>
      )}
      </Draggable>        
    );
  }

  const getItemStyle = (isDragging: boolean, draggableStyle: any) => ({
    ...draggableStyle,
    userSelect: "none",
    background: isDragging ? "rgb(79 79 79 / 70%)" : "",
  });

  const handleScroll = () => {
    if (!todoList.settings.general.isInfiniteScrollEnabled || infiniteScroll.isLoading) {
      return;
    }

    let { scrollTop, clientHeight, scrollHeight } = document.documentElement;

    if (todoList.settings.general.listSizeType === ListContainerType.Fixed) {
      scrollTop = document.getElementById('todo-list-container')!.scrollTop;
      clientHeight = document.getElementById('todo-list-container')!.clientHeight;      
      scrollHeight = document.getElementById('todo-list-container')!.scrollHeight;
    }

    if ((scrollTop + clientHeight >= scrollHeight - 20) 
     && !infiniteScroll.isLoading 
     && infiniteScroll.endIndex < todoList.originalList.length) {
      setInfiniteScroll({...infiniteScroll, isLoading: true });
      infiniteScroll.fetch.next(infiniteScroll.endIndex);
    }    
  };

  const reorder = (list: Array<ITodo>, startIndex: number, endIndex: number) => {
    if (todoList.settings.general.isPaginationEnabled) {
      startIndex = startIndex + ((todoList.paging.activePage - 1) * todoList.paging.itemsPerPage);
      endIndex =  endIndex + ((todoList.paging.activePage - 1)  * todoList.paging.itemsPerPage);
    }
    
    const result = Array.from(list);
    const [removed] = result.splice(startIndex, 1);
    result.splice(endIndex, 0, removed);
  
    return result;
  };

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  function onDragEnd(result: any) {
    // dropped outside the list
    if (!result.destination) {
      return;
    }

    const items = reorder(
      todoList.originalList,
      result.source.index,
      result.destination.index
    );

    items.forEach((item: ITodo, index: number) => item.sortId = index);

    dispatch({
      type: TodoActions.manuallySorted,
      payload: {
        list: items
      }      
    } as IAction);
  }

  return (
    <>
    { todoList.activeTab !== 'settings' && 
      <main 
        id="todo-list-container" 
        className="App__todo-list" 
        onScroll={handleScroll}     
        style={ 
          todoList.settings.general.listSizeType === ListContainerType.Fixed 
          ? { 
              height: todoList.settings.general.fixedListSize,
              overflow: 'overlay'
            } 
          : {}
          }
        >
        { 
          todoList.isLoading 
          ? <Loader height={280} />
          : <DragDropContext onDragEnd={onDragEnd}>
              <Droppable droppableId="droppable-list">
                {(provided, snapshot) => (
                <section 
                  id="todo-list-section"
                  className=''
                  {...provided.droppableProps}
                  ref={provided.innerRef}
                >
                  {
                    (todoList.paging.totalCount > 0 
                      ? getDisplayList() 
                      : <div className='text-light mt-5 mb-5 fade-in'>No data</div>)
                  }
                  {
                    todoList.settings.general.isInfiniteScrollEnabled &&
                    infiniteScroll.isLoading &&
                    <Loader height={150} />
                  }      
                  {provided.placeholder}        
                </section>
                )}
              </Droppable>
            </DragDropContext>
        }
        {
          todoList.settings.general.isInfiniteScrollEnabled 
          && !infiniteScroll.isLoading 
          && !todoList.isLoading 
          && infiniteScroll.endIndex < todoList.originalList.length 
          && todoList.displayMode === DisplayMode.All 
          && <div id="infinite-scroll-end" className="App__todo-list__infinite-scroll-end">
                <div className="App__todo-list__infinite-scroll-end--bouncing">
                  <FontAwesomeIcon icon={faAngleDown} />
                  <div>Scroll down to load more</div>
                </div>            
              </div>
        }      
      </main>
    }    
    </>
  );
}
