// react-workspace/todo-react-app/src/components/ConfirmModal.tsx
import Button from 'react-bootstrap/Button';
import Modal from 'react-bootstrap/Modal';

type Props = {
  content: string
  show: boolean,
  onConfirm: () => void
  onCancel: () => void
}

export function ConfirmModal({ content, show, onConfirm, onCancel }: Props) {

  return (
    <Modal
      id="confirm-modal"
      {...{show}}
      size="sm"
      aria-labelledby="contained-modal-title-vcenter"
      centered
    >
      <Modal.Body className="todo-background">
        <h5 className='text-center content-text'>
          {content}
        </h5>
      </Modal.Body>
      <Modal.Footer className="todo-background border-0 d-flex justify-content-center">
        <Button 
          onClick={onConfirm} 
          className="action-button btn-sm"
          variant="default"
        >
          Confirm
        </Button>
        <Button 
          onClick={onCancel} 
          variant="outline-light btn-sm" 
        >
          Cancel
        </Button>
      </Modal.Footer>
    </Modal>
  )
}

// todo-app-angular-workspace/projects/todo-app/src/app/components/confirm-modal/confirm-modal.component.ts
import { Component } from '@angular/core';
import { BsModalRef } from 'ngx-bootstrap/modal';
import { Subject } from 'rxjs';

@Component({
  selector: 'app-confirm-modal',
  templateUrl: './confirm-modal.component.html',
  styleUrls: ['./confirm-modal.component.scss']
})
export class ConfirmModalComponent {
  result: Subject<boolean> = new Subject();
  modalRef!: BsModalRef;
  text: string = 'Are you sure?';
  constructor() {}

  confirm(): void {
    this.result.next(true);
    this.modalRef?.hide();
  }

  decline(): void {
    this.result.next(false);
    this.modalRef?.hide();
  }
}

<div>
  <!-- <div class="modal-header">
    <button type="button" class="btn-close close pull-right" aria-label="Close" (click)="modalRef.hide()">
      <span aria-hidden="true" class="visually-hidden">&times;</span>
    </button>
  </div> -->
  <div class="modal-body text-center todo-background content-text">
    <h5>{{text}}</h5>
  </div>
  <div class="modal-footer todo-background border-0 d-flex justify-content-center">
    <button class="btn btn-sm action-button" (click)="confirm()" >Confirm</button>
    <button class="btn btn-sm btn-outline-light" (click)="decline()" >Cancel</button>
  </div>
</div>
