// todo-app-angular-workspace/projects/todo-app/src/app/components/todo-actions/todo-actions.component.ts
import { Component, OnInit } from '@angular/core';
import { Store } from '@ngrx/store';
import { Subscription, first } from 'rxjs';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { faTrash, faRotateLeft } from '@fortawesome/free-solid-svg-icons';

import { ConfirmModalService } from '..';
import { IState, TodoListActions, selectSettings } from '../../shared/state';
import { ISettings } from '../../shared/models';

@Component({
  standalone: true,
  imports: [FontAwesomeModule],
  selector: 'app-todo-actions',
  templateUrl: './todo-actions.component.html',
  styleUrls: ['./todo-actions.component.scss']
})
export class TodoActionsComponent implements OnInit {

  faTrash = faTrash;
  faRotateLeft = faRotateLeft;
  settings!: ISettings;
  private subscription!: Subscription;

  constructor(private store: Store<IState>, private modalService: ConfirmModalService) { }

  ngOnInit(): void {
    this.subscription = this.store.select(selectSettings)
        .pipe()
        .subscribe((settings: ISettings) => {
          this.settings = settings;
        });
  }

  onRestoreAll(): void {
    if (!this.settings?.general?.isConfirmEnabled) {
      this.store.dispatch(TodoListActions.restoredAll());
      return;
    }

    this.modalService.confirm('Are you sure you want to restore all items?', 'modal-sm')
    .pipe(first())
    .subscribe((confirmed) => {
      if (confirmed) {
        this.store.dispatch(TodoListActions.restoredAll());
      }
    });
  }

  onRemoveAll(): void {
    if (!this.settings?.general?.isConfirmEnabled) {
      this.store.dispatch(TodoListActions.removedAll());
      return;
    }

    this.modalService.confirm('Are you sure you want to remove all items?', 'modal-sm')
    .pipe(first())
    .subscribe((confirmed) => {
      if (confirmed) {
        this.store.dispatch(TodoListActions.removedAll());
      }
    });
  }
}

<div class="hstack gap-3 mt-2 mb-2">
  <div class="action-icon position-relative" (click)="onRestoreAll()">
    <fa-icon
      [icon]="faRotateLeft"
      class="action-icon-front"
    ></fa-icon>
    <fa-icon
      [icon]="faRotateLeft"
      class="action-icon-back"
    ></fa-icon>
  </div>
  <div class="action-icon position-relative" (click)="onRemoveAll()">
    <fa-icon
      [icon]="faTrash"
      class="action-icon-front"
    ></fa-icon>
    <fa-icon
      [icon]="faTrash"
      class="action-icon-back"
    ></fa-icon>
  </div>
</div>

// react-workspace/todo-react-app/src/components/TodoActions/TodoActions.tsx
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faTrash, faRotateLeft } from "@fortawesome/free-solid-svg-icons";
import { useState } from "react";

import { useTodoList, useTodoListDispatch } from "../../context";
import { ConfirmModal } from "../ConfirmModal/ConfirmModal";
import { Stack } from "react-bootstrap";
import { IAction, TodoActions as TodoStateActions } from "../../models";

export function TodoActions() {
  const todoList = useTodoList();
  const dispatch = useTodoListDispatch();

  const [showModal, setShowModal] = useState(false);
  const [confirmDialogText, setConfirmDialogText] = useState('');
  const [confirm, onConfirm] = useState<null | (() => void)>(null);

  function handleRestoreAll() {
    dispatch({
      type: TodoStateActions.restoredAll,
    } as IAction);
  }

  function handleDeleteAll() {
    dispatch({
      type: TodoStateActions.deletedAll,
    } as IAction);
  }


  return (
    <div className="ms-auto">
      <Stack direction="horizontal" gap={3} className="mt-2 mb-2">
        <div
          data-testid="restore-all-button"
          className="action-icon position-relative"
          onClick={() => {
            if (todoList.settings.general.isConfirmEnabled) {
              onConfirm(() => handleRestoreAll);
              setConfirmDialogText('Are you sure you want to restore all items?');
              setShowModal(true);

              return;
            }

            handleRestoreAll();
          }} 
        >
          <FontAwesomeIcon 
            icon={faRotateLeft}
            className="action-icon-front"
          />
          <FontAwesomeIcon
            icon={faRotateLeft}
            className="action-icon-back"
          />
        </div>
        <div         
          data-testid="delete-all-button"
          className="action-icon position-relative"
          onClick={() => {
            if (todoList.settings.general.isConfirmEnabled) {
              onConfirm(() => handleDeleteAll);
              setConfirmDialogText('Are you sure you want to delete all items?');
              setShowModal(true);

              return;
            }

            handleDeleteAll();
          }}
        >
          <FontAwesomeIcon
            icon={faTrash} 
            className="action-icon-front"
          />
          <FontAwesomeIcon 
            icon={faTrash} 
            className="action-icon-back"
          />
        </div>
      </Stack>
      <ConfirmModal
        content={confirmDialogText} 
        show={showModal}
        onConfirm={() => { 
          ((confirm!)());
          setShowModal(false);
        }}
        onCancel={() => setShowModal(false)}
      />
    </div>
  );
}
