// todo-app-angular-workspace/projects/todo-app/src/app/filter-todos/filter-todos.component.ts
import { Component, OnInit } from '@angular/core';
import { Store } from '@ngrx/store';
import { ITodoList } from '../shared/models/todoList';
import { TodoListActions } from '../state/todo.actions';
import { selectFilter } from '../state/todo.selectors';

@Component({
  selector: 'app-filter-todos',
  templateUrl: './filter-todos.component.html',
  styleUrls: ['./filter-todos.component.scss']
})
export class FilterTodosComponent implements OnInit {
  isCompleted = false;
  isUncompleted = false;

  constructor(private store: Store<ITodoList>) { }

  ngOnInit(): void { 
    this.store.select(selectFilter)
        .pipe()
        .subscribe((filter: any) => {
          this.isCompleted = filter.completed;
          this.isUncompleted = filter.uncompleted;
        });
  }

  onFilter(): void {
    this.store.dispatch(TodoListActions.filtered({ 
      activePage: 1,
      filter: {
        completed: this.isCompleted,
        uncompleted: this.isUncompleted
      }
    }));
  }
}

<div class="app__filter d-flex justify-content-start align-items-center p-0">
  <div class="hstack gap-3">
    <div>
      <mat-slide-toggle [(ngModel)]="isCompleted" (click)="onFilter()">
        Completed
      </mat-slide-toggle>
    </div>
    <div>
      <mat-slide-toggle [(ngModel)]="isUncompleted" (click)="onFilter()">
        Uncompleted
      </mat-slide-toggle>
    </div>
  </div>
</div>

// react-workspace/todo-react-app/src/components/FilterTodos.tsx
import { Form, Stack } from "react-bootstrap";
import { useTodoList, useTodoListDispatch } from "../context/TodosContext";

export function FilterTodos() {
  const todoList = useTodoList();
  const dispatch = useTodoListDispatch();

  function onFilter(completed: any, uncompleted: any) {
    dispatch({
      type: 'filtered',
      activePage: 1,
      filter: { 
        completed: completed,
        uncompleted: uncompleted
      }
    });
  }

  return (
    <Form className="App__filter d-flex justify-content-start align-items-center">
      <Stack direction="horizontal" gap={3}>       
        <Form.Check 
          type="switch"
          id={`completed`}
          label={`Completed`}
          checked={todoList.filter.completed}
          onChange={(e) => {
            onFilter(e.target.checked, todoList.filter.uncompleted);
          }}
        />   
        <Form.Check 
          type="switch"
          id={`uncompleted`}
          label={`Uncompleted`}
          checked={todoList.filter.uncompleted}
          onChange={(e) => {
            onFilter(todoList.filter.completed, e.target.checked);
          }}
        />         
      </Stack>
    </Form>
  )
}
