// todo-app-angular-workspace/projects/todo-app/src/app/components/filter-todos/filter-todos.component.ts
import { Component, OnInit } from '@angular/core';
import { Store } from '@ngrx/store';
import { first } from 'rxjs';
import { IFilter } from '../../shared/models/filter';
import { ITodo } from '../../shared/models/todo';
import { IState } from '../../shared/state/state';
import { TodoService } from '../../shared/services/todo.service';
import { TodoListActions } from '../../shared/state/todo.actions';
import { selectFilter, selectTodos } from '../../shared/state/todo.selectors';

@Component({
  selector: 'app-filter-todos',
  templateUrl: './filter-todos.component.html',
  styleUrls: ['./filter-todos.component.scss']
})
export class FilterTodosComponent implements OnInit {
  isCompleted = false;
  isUncompleted = false;

  constructor(private store: Store<IState>, private todoService: TodoService) { }

  ngOnInit(): void {
    this.store.select(selectFilter)
        .pipe()
        .subscribe((filter: IFilter) => {
          this.isCompleted = filter.completed;
          this.isUncompleted = filter.uncompleted;
        });
  }

  onFilter(): void {
    this.store.dispatch(TodoListActions.loadingStarted());
    this.store.select(selectTodos)
    .pipe(first())
    .subscribe((todoList: IState) => {
      const filter = {
        completed: this.isCompleted,
        uncompleted: this.isUncompleted
      } as IFilter;

      this.todoService.getList(
        filter,
        todoList.sort,
        todoList.search.searchTerm)
        .pipe(first())
        .subscribe((list: ITodo[]) => {
          this.store.dispatch(TodoListActions.filtered({
            activePage: 1,
            filter,
            list: list
          }));
      });
    });


  }
}

<div class="app__filter d-flex justify-content-start align-items-center">
  <div class="hstack gap-3">
    <!-- <div>
      <mat-slide-toggle [(ngModel)]="isCompleted" (click)="onFilter()">
        Completed
      </mat-slide-toggle>
    </div>
    <div>
      <mat-slide-toggle [(ngModel)]="isUncompleted" (click)="onFilter()">
        Uncompleted
      </mat-slide-toggle>
    </div> -->
    <div
      class="btn-group"
      dropdown
    >
      <button
        id="button-basic"
        dropdownToggle
        type="button"
        class="action-button dropdown-toggle btn btn-outline-secondary"
        aria-controls="dropdown-paging"
        [disabled]="isLoading$ | async"
      >
        {{stateFilter}}
      </button>
      <ul id="dropdown-paging" *dropdownMenu class="dropdown-menu"
          role="menu" aria-labelledby="button-paging">
        <li role="menuitem" (click)="onFilter(StateFilter.all)"><a class="dropdown-item" href="#">{{StateFilter.all}}</a></li>
        <li role="menuitem" (click)="onFilter(StateFilter.completed)"><a class="dropdown-item" href="#">{{StateFilter.completed}}</a></li>
        <li role="menuitem" (click)="onFilter(StateFilter.uncompleted)"><a class="dropdown-item" href="#">{{StateFilter.uncompleted}}</a></li>
      </ul>
    </div>
  </div>
</div>

// react-workspace/todo-react-app/src/components/FilterTodos.tsx
import { useState } from "react";
import { Form, Stack } from "react-bootstrap";
import { first } from "rxjs";
import Dropdown from 'react-bootstrap/Dropdown';
import { useTodoList, useTodoListDispatch } from "../context/TodoListContext";
import { IAction } from "../models/Action";
import { IFilter, StateFilter } from "../models/IFilter";
import { ITodo } from "../models/Todo";
import { getList, GetListProps } from "../providers/TodoProvider";
import { localStorageProvider } from "../providers/StorageProvider";

type Props = { 
  filter: IFilter
}

export function FilterTodos({ filter }: Props) {
  const todoList = useTodoList();
  const dispatch = useTodoListDispatch();

  // const [completedSwitch, setCompletedSwitch] = useState(completed);
  // const [uncompletedSwitch, setetUncompletedSwitch] = useState(uncompleted);
  const [stateFilter, setStateFilter] = useState(filter.state);

  function handleStateFilter(filterValue: StateFilter) {
    setStateFilter(filterValue);
    dispatch({
      type: 'loading-started'
    } as IAction);
    const filter = { 
      state: filterValue
    } as IFilter;

    getList({
      provider: localStorageProvider,
      filter, 
      sort: todoList.sort,
      searchTerm: todoList.search.searchTerm
      } as GetListProps)
    .pipe(first())
    .subscribe((list: ITodo[]) => { 
      dispatch({
        type: 'filtered',
        payload: {
          activePage: 1,
          list: list,
          filter: { 
            state: filterValue
          } as IFilter
        }
      } as IAction);
    });
  }

  return (
    <Form className="App__filter d-flex justify-content-start align-items-center">
      <Stack direction="horizontal" gap={3}>       
        {/* <Form.Check 
          type="switch"
          id={`completed`}
          label={`Completed`}
          checked={completedSwitch}
          onChange={(e) => {
            setCompletedSwitch(e.target.checked);
            handleFilter(e.target.checked, uncompleted);
          }}
        />   
        <Form.Check 
          type="switch"
          id={`uncompleted`}
          label={`Uncompleted`}
          checked={uncompletedSwitch}
          onChange={(e) => {
            setetUncompletedSwitch(e.target.checked);
            handleFilter(completed, e.target.checked);
          }}
        /> */}
         <Dropdown>
            <Dropdown.Toggle
              variant="outline-secondary"
              className="action-button ps-2 pe-2"
              id="dropdown-basic"
              disabled={todoList.isLoading}
            >
              {' '}{stateFilter}{' '}
            </Dropdown.Toggle>

            <Dropdown.Menu>
              <Dropdown.Item onClick={() => handleStateFilter(StateFilter.all)}>All</Dropdown.Item>
              <Dropdown.Item onClick={() => handleStateFilter(StateFilter.completed)}>Completed</Dropdown.Item>
              <Dropdown.Item onClick={() => handleStateFilter(StateFilter.uncompleted)}>Uncompleted</Dropdown.Item>
            </Dropdown.Menu>
          </Dropdown>
      </Stack>

    </Form>
  )
}
