// todo-app-angular-workspace/projects/todo-app/src/app/components/sorting/sorting.component.ts
import { Component, OnInit } from '@angular/core';

type Sort = {
  name: string,
  text: string
}

@Component({
  selector: 'app-sorting',
  templateUrl: './sorting.component.html',
  styleUrls: ['./sorting.component.scss']
})
export class SortingComponent implements OnInit {
  sortByColumns: Sort[] = [
    {
      name: 'title',
      text: 'Title'
    } as Sort,
    {
      name: 'description',
      text: 'Description'
    } as Sort,
    {
      name: 'createdAt',
      text: 'Date'
    } as Sort,
    {
      name: 'completed',
      text: 'Completed'
    } as Sort
  ];

  constructor() { }

  ngOnInit(): void { }
}

<section class="app__sorting d-flex flex-wrap">
  <app-sort-button
    *ngFor="let column of sortByColumns"
    [text]="column.text"
    [column]="column.name"
    [sortType]="column.sortType"
    [isActive]="activeColumn == column.name"
    [sortDirection]="activeColumn === column.name ? SortDirection.Asc : SortDirection.None"
    (onSort)="handleSort($event)"
  ></app-sort-button>
</section>

// react-workspace/todo-react-app/src/components/Sorting.tsx
import { SortButton } from './SortButton';

type Sort = {
  name: string,
  text: string
}

const sortByColumns: Sort[] = [
  {
    name: 'title',
    text: 'Title'
  } as Sort,
  {
    name: 'description',
    text: 'Description'
  } as Sort,
  {
    name: 'createdAt',
    text: 'Date'
  } as Sort,
  {
    name: 'completed',
    text: 'Completed'
  } as Sort
];

export function Sorting() {
  return (
    <section className="App__sorting d-flex flex-wrap">
      {
        sortByColumns.map((item: Sort) => (
          <SortButton 
            key={item.name}
            column={item.name}
            text={item.text}
          />
        ))
      }
    </section>
  );
}
