// todo-app-angular-workspace/projects/todo-app/src/app/components/sort-button/sort-button.component.ts
import { Component, Input } from '@angular/core';
import { Store } from '@ngrx/store';
import { first } from 'rxjs';
import { ISort, SortDirection } from '../../shared/models/sort';
import { IState } from '../../shared/state/state';
import { TodoService } from '../../shared/services/todo.service';
import { TodoListActions } from '../../shared/state/todo.actions';
import { selectSort, selectTodos } from '../../shared/state/todo.selectors';
import { ITodo } from '../../shared/models/todo';

@Component({
  selector: 'app-sort-button',
  templateUrl: './sort-button.component.html',
  styleUrls: ['./sort-button.component.scss']
})
export class SortButtonComponent {
  @Input() column: string = "";
  @Input() text: string = "";

  sortDirection!: string;

  constructor(private store: Store<IState>, private todoService: TodoService) {}

  ngOnInit(): void {
    this.store.select(selectSort)
    .pipe()
    .subscribe((sort: ISort) => {
      this.sortDirection = sort.column === this.column ? sort.direction : SortDirection.None;
    });
  }

  sort(): void {
    this.store.dispatch(TodoListActions.loadingStarted());
    this.store.select(selectTodos)
    .pipe(first())
    .subscribe((todoList: IState) => {
      const sort = {
        column: this.column,
        direction: this.sortDirection !== SortDirection.Asc ? SortDirection.Asc : SortDirection.Desc
      } as ISort;

      this.todoService.getList(
        todoList.filter,
        sort,
        todoList.search.searchTerm)
        .pipe(first())
        .subscribe((list: ITodo[]) => {
          this.store.dispatch(TodoListActions.sorted({
            sort,
            list
          }));
      });
    });
  }
}

<div
  class="app__sorting__item"
  (click)="onSort()"
  [ngClass]="{'app__sorting__item--disabled': isLoading}"
>
  <span>{{text}}</span>
  <app-sort-icon [sortDirection]="sortDirection"></app-sort-icon>
</div>

// react-workspace/todo-react-app/src/components/SortButton.tsx
import { useEffect, useState } from "react";
import { first } from "rxjs";
import { useTodoList, useTodoListDispatch } from "../context/TodoListContext";
import { IAction } from "../models/Action";
import { SortDirection } from "../models/ISort";
import { ITodo } from "../models/Todo";
import { todoServiceInstance } from "../services/TodoService";
import { SortIcon } from "./SortIcon";

type Props = {
  column: string,
  text: string
};

export function SortButton({ column, text }: Props) {
  const todoList = useTodoList();
  const dispatch = useTodoListDispatch();
  const [direction, setDirection] = useState(todoList.sort.column === column ? todoList.sort.direction : SortDirection.None);

  useEffect(() => {     
    setDirection(todoList.sort.column === column ? todoList.sort.direction : SortDirection.None);
  }, [column, todoList.sort.column, todoList.sort.direction])

  return(
    <div className="App__sorting__item" onClick={() => { 
        const newDirectionState = direction !== SortDirection.Asc ? SortDirection.Asc : SortDirection.Desc;
        setDirection(newDirectionState);
        const sort = {
          column: column, 
          direction: newDirectionState
        }
        todoServiceInstance.getList(
          todoList.filter, 
          sort,
          todoList.search.searchTerm)
          .pipe(first())
          .subscribe((list: ITodo[]) => { 
            dispatch({
              type: 'sorted',
              payload: {
                sort,
                list: list
              }
            } as IAction);
        });
      }}
    >
      <span>{text}</span> 
      <SortIcon sortDirection={direction}/>
    </div>
  )
}
