// todo-app-angular-workspace/projects/todo-app/src/app/components/tabs/tabs.component.ts
import { Component } from '@angular/core';
import { faAdd, faSearch, faFilter, faDownload, IconDefinition } from '@fortawesome/free-solid-svg-icons';

type Tab = {
  name: string,
  icon: IconDefinition,
}

@Component({
  selector: 'app-tabs',
  templateUrl: './tabs.component.html',
  styleUrls: ['./tabs.component.scss']
})
export class TabsComponent {
  tabs: Tab[] = [{
      name: 'add-todo',
      icon: faAdd,
    } as Tab,
    {
      name: 'search-todos',
      icon: faSearch
    } as Tab,
    {
      name: 'filter-todos',
      icon: faFilter
    } as Tab,
    {
      name: 'import-export',
      icon: faDownload
    } as Tab
  ];

  active = 'add-todo'

  setTab(name: string): void {
    this.active = name;
  }
}

<section class="app__tabs mb-2">
  <section class="app__tabs__header">
    <div id="tabs" class="hstack gap-1 align-items-end">
      <div
        *ngFor="let tab of tabs; trackBy:tabTrackBy"
        [id]="tab.name"
        class="app__tabs__item"
        [ngClass]="{'app__tabs__item--inactive': active !== tab.name}"
        (click)="setTab(tab.name)"
      >
        <fa-icon [icon]="tab.icon"></fa-icon>
      </div>
    </div>
  </section>
  <section class="app__tabs__content">
    <div class="todo-background">
      <app-add-todo *ngIf="active === 'add-todo'" class="fade-in"></app-add-todo>
      <app-search-todos *ngIf="active === 'search-todos'" class="fade-in"></app-search-todos>
      <app-filter-todos *ngIf="active === 'filter-todos'" class=""></app-filter-todos>
      <app-import-export *ngIf="active === 'import-export'" class="fade-in"></app-import-export>
      <app-todo-settings *ngIf="active === 'todo-settings'" class="fade-in"></app-todo-settings>
    </div>
  </section>
</section>

// react-workspace/todo-react-app/src/components/Tabs.tsx
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faSearch, faAdd, faFilter, faDownload } from '@fortawesome/free-solid-svg-icons';
import { Stack } from "react-bootstrap";
import { useState } from "react";

export function Tabs({ children }: any) {
  const [active, setActive] = useState('add-todo');
  const activeChild = children.find((item: any) => item.key === active);
  const tabs = [{
    name: 'add-todo',
    icon: faAdd,
  },
  {
    name: 'search-todos',
    icon: faSearch
  },
  {
    name: 'filter-todos',
    icon: faFilter
  },
  {
    name: 'import-export',
    icon: faDownload
  }
];

  return (
    <section className="App__tabs mb-2">
      <Stack direction="horizontal" gap={1}>      
        {tabs.map((tab: any) => (
          <div 
            key={tab.name}
            className={ 
              active === tab.name 
              ? "App__tabs__item" 
              : "App__tabs__item App__tabs__item--inactive"
            } 
            onClick={()=> setActive(tab.name)}
          >      
            <FontAwesomeIcon icon={tab.icon} />
          </div>
        ))}
      </Stack>
      <section className="App__tabs-content">
        <div 
          key={"tab-content-" + activeChild.key}
          className="fade-in"
        >
          {activeChild}
        </div>
      </section>     
    </section>
  )
}
