// todo-app-angular-workspace/projects/todo-app/src/app/components/add-todo/add-todo.component.ts
import { Store } from '@ngrx/store';
import { Component, OnInit } from '@angular/core';
import { TodoListActions } from '../../shared/state/todo.actions';
import { ITodoList } from '../../shared/models/todoList';

@Component({
  selector: 'app-add-todo',
  templateUrl: './add-todo.component.html',
  styleUrls: ['./add-todo.component.scss']
})
export class AddTodoComponent implements OnInit {
  title = ''
  description = ''

  constructor(private store: Store<ITodoList>) { }

  ngOnInit(): void { }
  
  async onAdd() {
    this.store.dispatch(TodoListActions.added({
      title: this.title,
      description: this.description,
    }));
  }

  get ifDataIsMissing(): boolean {
    return !this.title 
      || this.title.trim() === '' 
      || !this.description 
      || this.description.trim() === ''
  }
}

<div class="container-fluid">
  <div class="row p-1">
    <div class="col-12 col-sm-5 p-2">
      <input 
        type="text" 
        class="form-control form-control-sm" 
        id="title" 
        placeholder="Enter title"
        [(ngModel)]="title"
      />
    </div>
    <div class="col-12 col-sm-5 p-2">
      <input 
        type="text" 
        class="form-control form-control-sm" 
        id="description" 
        placeholder="Enter description"
        [(ngModel)]="description"
      />
    </div>
    <div class="col-12 col-sm-2 p-2">
      <button 
        type="submit" 
        class="btn btn-sm btn-outline-secondary action-button w-100"
        [disabled]="ifDataIsMissing"
        (click)="onAdd()"
      >
        Add
      </button>
    </div>
  </div>
</div>

// react-workspace/todo-react-app/src/components/AddTodo/AddTodo.tsx
import { Button, Col, Container, Form, Row } from 'react-bootstrap';
import { useState } from 'react';
import { useTodoListDispatch } from '../../context/TodoListContext';
import { IAction } from '../../models/Action';

export function AddTodo() {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');

  const dispatch = useTodoListDispatch();

  function handleAdd() {
    dispatch({
      type: 'added',
      payload: {
        title, 
        description
      }
    } as IAction);
    setTitle('');
    setDescription('');
  }
  
  return (
    <Form className="todo-background p-1">
      <Container fluid>
        <Row xs={1} sm={3}>
          <Col sm={5} className="p-2">
            <Form.Control 
              id="title"
              data-testid="title-input"
              name="title"
              type="text" 
              placeholder="Enter title" 
              size="sm" 
              value={title}
              onChange={(e) => setTitle(e.target.value)} 
            />
          </Col>
          <Col sm={5} className="p-2">
            <Form.Control 
              id="description"
              data-testid="description-input"
              name="description"
              type="text" 
              placeholder="Enter description" 
              size="sm" 
              value={description}
              onChange={(e) => setDescription(e.target.value)} 
            />
          </Col>
          <Col sm={2} className="p-2">
            <Button 
              data-testid="add-todo-button"
              variant="outline-secondary"
              className="action-button w-100"
              size="sm"
              disabled={title.trim() === '' || description.trim() === ''}
              onClick={handleAdd}
            >
              Add
            </Button>
          </Col>
        </Row>
      </Container>
    </Form>
  )
}
