// react-workspace/todo-react-app/src/components/TodoItem.tsx
import { Button, Stack } from 'react-bootstrap';
import { useTodoListDispatch } from '../context/TodosContext';
import { ITodo } from '../models/Todo';

const buttonStyle : any = { 
  backgroundColor: '#F5F6F7', 
  borderRadius: '20px', 
  minWidth: '90px'
}

type Props = {
  todo: ITodo;
};

export function TodoItem({ todo }: Props){

  const dispatch = useTodoListDispatch();

  return (
      <div className="App__todo-list__item">
        <Stack direction="horizontal" gap={3}>
          <div>
            <div className={ todo.completed 
                ? "App__todo-list__item-title--completed" 
                : "App__todo-list__item-title" 
            }>
              { todo.title }
            </div>
            <div className={
              todo.completed 
                ? "App__todo-list__item-description--compleated" 
                : "App__todo-list__item-description"
              }>
                <span>{todo.description}</span>
                <span>
                  {' ' + new Date(todo.createdAt).toDateString() + ' '}
                </span>
            </div>
          </div>     
          { !todo.completed &&
            <Button 
              className="ms-auto"
              variant="outline-success" 
              size="sm"
              style={ buttonStyle }
              onClick={() => {
                dispatch({
                  type: 'changed',
                  todo: {...todo, completed: true}
                });
              }}
            >
              Complete
            </Button>
          }
          <Button 
            className= { todo.completed ? "ms-auto" : "" } 
            variant="outline-danger" 
            size="sm" 
            style={ buttonStyle }
            onClick={() => {
              dispatch({
                type: 'deleted',
                id: todo.id
              });
            }}
          >
            Delete
          </Button>
        </Stack>
      </div>
  )
}

// todo-app-angular-workspace/projects/todo-app/src/app/todo-item/todo-item.component.ts
import { Component, Input } from '@angular/core';
import { ITodo } from '../shared/models/todo';

@Component({
  selector: 'app-todo-item',
  templateUrl: './todo-item.component.html',
  styleUrls: ['./todo-item.component.scss']
})
export class TodoItemComponent {

  @Input() todo: ITodo = {} as ITodo;
  buttonStyle : any = { 
    backgroundColor: '#F5F6F7', 
    borderRadius: '20px', 
    minWidth: '90px'
  }
}

<div class="app__todo-list__item">
  <div class="hstack gap-3">
    <div class="">
      <div [ngClass]="todo.completed ? 'app__todo-list__item-title--completed' : 'app__todo-list__item-title'">
        {{ todo.title }}
      </div>
      <div [ngClass]="todo.completed ? 'app__todo-list__item-description--compleated' : 'app__todo-list__item-description'">
        <span>{{ todo.description }}</span>
        <span>{{ todo.createdAt | date }}</span>
      </div>
    </div>
    <div class="ms-auto">
      <button 
        *ngIf="!todo.completed" 
        [ngStyle]="buttonStyle" 
        class="btn btn-outline-success btn-sm"
      >
        Complete
      </button>
    </div>
    <div [ngClass]="{'ms-todo' : todo.completed}">
      <button [ngStyle]="buttonStyle" class="btn btn-outline-danger btn-sm">
        Delete
      </button>
    </div>
  </div>
</div>
